# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bhavatoshr\Desktop\DGT\Finals\Homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 342)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Home_main = QtWidgets.QWidget(self.centralwidget)
        self.Home_main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Home_main.setObjectName("Home_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Home_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Home_main_1 = QtWidgets.QLabel(self.Home_main)
        self.Home_main_1.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Home_main_1.setFont(font)
        self.Home_main_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Home_main_1.setObjectName("Home_main_1")
        self.verticalLayout.addWidget(self.Home_main_1, 0, QtCore.Qt.AlignHCenter)
        self.textBrowser = QtWidgets.QTextBrowser(self.Home_main)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout.addWidget(self.Home_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Home_main_1.setText(_translate("MainWindow", "Welcome"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">The Data Governance Framework establishes enterprise-wide required process and controls in support of Payments Network data strategy. Pursuant to the Enterprise Data Management Policy, all impacted Business Units are required to support the implementation of each phase in accordance with the Data Management Framework’s established timeframe. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">Compliance to the framework will be monitored and tracked by this tool. This tool provides the checklist for </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">implementation of the data governance pillars:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#000000;\">• </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; font-weight:600; color:#000000;\">Data Cataloging: </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">Enable consistent data sharing across the enterprise and document lineage. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#000000;\">• </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; font-weight:600; color:#000000;\">Data Classification: </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">Identify Critical Data Elements (CDEs); classify how data elements are used, governed and secured. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#000000;\">• </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; font-weight:600; color:#000000;\">Data Quality: </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">Determine business rules that generate alerts when there are data inconsistencies; ensure that data reconciles as it moves across systems. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#000000;\">• </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; font-weight:600; color:#000000;\">Data Lifecycle: </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">Track data assets across its lifecycle around creation, usage, enrichment and retention </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#000000;\">• </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; font-weight:600; color:#000000;\">Compliance: </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">Manage risk and compliance across all processes and monitoring capabilities. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#000000;\">• </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; font-weight:600; color:#000000;\">Management Reporting: </span><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">Create management visibility on KPIs and KRIs in order to be able to track the performance of the systems and applications being monitored</span><span style=\" font-size:10pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Calibri 53\'; font-size:10pt; color:#000000;\">All the impacted cross functional teams and downstream systems can acknowledge the initiative changes and data impacts at each phase of C360 Process using the workflowbuilt in the tool.</span><span style=\" font-size:10pt;\"> </span></p></body></html>"))
