# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\bhavatoshr\Desktop\DGT\CV_WELCOME.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 311)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.CV_START_Page = QtWidgets.QWidget()
        self.CV_START_Page.setObjectName("CV_START_Page")
        self.CV_START_Page_GL = QtWidgets.QGridLayout(self.CV_START_Page)
        self.CV_START_Page_GL.setObjectName("CV_START_Page_GL")
        self.CV_Welcome_L2 = QtWidgets.QLabel(self.CV_START_Page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CV_Welcome_L2.setFont(font)
        self.CV_Welcome_L2.setAlignment(QtCore.Qt.AlignCenter)
        self.CV_Welcome_L2.setObjectName("CV_Welcome_L2")
        self.CV_START_Page_GL.addWidget(self.CV_Welcome_L2, 1, 0, 1, 2)
        self.CV_Welcome_L = QtWidgets.QLabel(self.CV_START_Page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.CV_Welcome_L.setFont(font)
        self.CV_Welcome_L.setAlignment(QtCore.Qt.AlignCenter)
        self.CV_Welcome_L.setObjectName("CV_Welcome_L")
        self.CV_START_Page_GL.addWidget(self.CV_Welcome_L, 0, 0, 1, 2)
        self.footer = QtWidgets.QFrame(self.CV_START_Page)
        self.footer.setMinimumSize(QtCore.QSize(0, 50))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 70))
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.CV_START_Page_GL.addWidget(self.footer, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.CV_START_Page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CV_Welcome_L2.setText(_translate("MainWindow", "Create,edit,upload with description"))
        self.CV_Welcome_L.setText(_translate("MainWindow", "Concept Validation"))
